MvcWebIdentityA/Controllers/AlunosController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MvcWebIdentityA.Context;
using MvcWebIdentityA.Entities;

namespace MvcWebIdentityA.Controllers
{
    [Authorize]
    [Authorize(Roles = "Admin, User , Gerente")]
    
    [Authorize]
    [Authorize(Roles = "Admin")]
    public class AlunosController : Controller
    {
        private readonly AppDbContext _context;

        public AlunosController(AppDbContext context)
        {
            _context = context;
        }

        [AllowAnonymous] // dara acesso a todos aos Usuários, mesmo não estando autenticado
        // GET: Alunos
        [AllowAnonymous] // dara acesso a todos aos Usuários, mesmo não estando autenticado

        // GET: Alunos
        public async Task<IActionResult> Index()
        {
            return View(await _context.Alunos.ToListAsync());
        }

        //[Authorize(Roles = "User, Admin, Gerente")]
        [Authorize(Policy = "RequireUserAdminGerenteRole")]
        // GET: Alunos/Details/5
        //[Authorize(Roles = "User, Admin, Gerente")]
        [Authorize(Policy = "RequireUserAdminGerenteRole")]
        // GET: Alunos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aluno = await _context.Alunos
                .FirstOrDefaultAsync(m => m.AlunoId == id);
            if (aluno == null)
            {
                return NotFound();
            }

            return View(aluno);
        }

        [Authorize(Roles = "Admin, Gerente")]
        //[Authorize(Policy = "RequireUserAdminGerenteRole")]

        // GET: Alunos/Create

        //[Authorize(Roles = "User, Admin, Gerente")]
        [Authorize(Policy = "RequireUserAdminGerenteRole")]

        // GET: Alunos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Alunos/Create

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AlunoId,Nome,Email,Idade,Curso")] Aluno aluno)
        {
            if (ModelState.IsValid)
            {
                _context.Add(aluno);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(aluno);
        }

        [Authorize(Roles = "Admin, Gerente")]
        // GET: Alunos/Edit/5

        [Authorize(Roles = "Admin, Gerente")]

        // GET: Alunos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aluno = await _context.Alunos.FindAsync(id);
            if (aluno == null)
            {
                return NotFound();
            }
            return View(aluno);
        }

        // POST: Alunos/Edit/5

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AlunoId,Nome,Email,Idade,Curso")] Aluno aluno)
        {
            if (id != aluno.AlunoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(aluno);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AlunoExists(aluno.AlunoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(aluno);
        }

        [Authorize(Roles = " Admin")]

        // GET: Alunos/Delete/5

        [Authorize(Roles = " Admin")]

        // GET: Alunos/Delete/5

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aluno = await _context.Alunos
                .FirstOrDefaultAsync(m => m.AlunoId == id);
            if (aluno == null)
            {
                return NotFound();
            }

            return View(aluno);
        }

        // POST: Alunos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var aluno = await _context.Alunos.FindAsync(id);
            if (aluno != null)
            {
                _context.Alunos.Remove(aluno);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AlunoExists(int id)
        {
            return _context.Alunos.Any(e => e.AlunoId == id);
        }
    }
}

MvcWebIdentityA/Controllers/ProdutosController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MvcWebIdentityA.Context;
using MvcWebIdentityA.Entities;

namespace MvcWebIdentityA.Controllers;

[Authorize]
public class ProdutosController : Controller
{
    private readonly AppDbContext _context;

    public ProdutosController(AppDbContext context)
    {
        _context = context;
    }

    [AllowAnonymous]
    public async Task<IActionResult> Index() => _context.Produtos != null
        ? View(await _context.Produtos.AsNoTracking().ToListAsync())
        : Problem("Entity set 'AppDbContext.Produtos' é null.");

    [Authorize(Policy = "IsFuncionarioClaimAccess")]
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null) return NotFound();

        var produto = await _context.Produtos.AsNoTracking().FirstOrDefaultAsync(m => m.ProdutoId == id);
        return produto == null ? NotFound() : View(produto);
    }

    [Authorize(Policy = "IsFuncionarioClaimAccess")]
    public IActionResult Create() => View();

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("ProdutoId, Nome, Preco")] Produto produto)
    {
        if (!ModelState.IsValid) return View(produto);

        _context.Produtos.Add(produto);
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    [Authorize(Policy = "IsAdminClaimAccess")]
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null) return NotFound();

        var produto = await _context.Produtos.FindAsync(id);
        return produto == null ? NotFound() : View(produto);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [Bind("ProdutoId, Nome, Preco")] Produto produto)
    {
        if (id != produto.ProdutoId) return NotFound();

        if (!ModelState.IsValid) return View(produto);

        try
        {
            _context.Update(produto);
            await _context.SaveChangesAsync();
        }
        catch (DbUpdateConcurrencyException)
        {
            if (!await ProdutoExists(produto.ProdutoId)) return NotFound();
            throw;
        }

        return RedirectToAction(nameof(Index));
    }

    [Authorize(Policy = "IsAdminClaimAccess")]
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null || _context.Produtos == null)
        {
            return NotFound();
        }

        var produto = await _context.Produtos.AsNoTracking().FirstOrDefaultAsync(m => m.ProdutoId == id);

        return produto == null ? NotFound() : View(produto);
    }

    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var produto = await _context.Produtos.FindAsync(id);
        if (produto == null) return NotFound();

        _context.Produtos.Remove(produto);
        await _context.SaveChangesAsync();

        return RedirectToAction(nameof(Index));
    }

    private async Task<bool> ProdutoExists(int produtoId) => await _context.Produtos.AnyAsync(e => e.ProdutoId == produtoId);
}

MvcWebIdentityA/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Identity</title>

    <!-- Estilos principais -->
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcWebIdentityA.styles.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">

</head>

<body>
    <!-- Cabeçalho e navegação -->
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-white shadow-sm mb-3">
            <div class="container-fluid">
                <!-- Logo com ícone -->
                <a class="navbar-brand d-flex align-items-center" asp-area="" asp-controller="Home" asp-action="Index">
                    <i class="bi bi-shield-lock me-2" style="font-size: 24px;"></i> Identity
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <!-- Menu de navegação -->
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">
                                <i class="bi bi-house-door me-2"></i>Home
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Alunos" asp-action="Index">
                                <i class="bi bi-person-circle me-2"></i>Alunos
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produtos" asp-action="Index">
                                <i class="bi bi-person-circle me-2"></i>Produtos
                            </a>
                        </li>
                        <partial name="_LoginAdmin.cshtml" />
                    </ul>
                    <partial name="_LoginPartial.cshtml" />
                </div>
            </div>
        </nav>
    </header>


    <!-- Conteúdo principal -->
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!-- Rodapé -->
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - MvcWebIdentityA - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <!-- Scripts -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

MvcWebIdentityA/Views/Shared/_LoginAdmin.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserInManager

@if (SignInManager.IsSignedIn(User))
{
    @if (User.IsInRole("Admin"))
    {
        <li class="nav-item">
            <!-- Link do Admin com ícone e um estilo mais moderno -->
            <a class="nav-link text-dark d-flex align-items-center"
               asp-area="Admin" asp-controller="Admin" asp-action="Index">
                <i class="bi bi-shield-lock mr-2"></i> Admin
            </a>
        </li>
    }
}